kotlin_library(
    name = 'bff-lib',
    srcs = glob(['**/*.kt']),
    deps = [
        '//libs/kotlin/stdlib:kotlin-stdlib',
        '//libs/ktor/server-host-common:ktor-server-host-common',
        '//libs/ktor/server-netty:ktor-server-netty'
    ],
    visibility = [
        '//bff/main:bff-app'
    ]
)

java_binary(
    name = 'bff-app',
    main_class = 'study.template.BffKt',
    deps = [
        '//bff/main:bff-lib'
    ]
)
