# https://github.com/hamcrest/JavaHamcrest
# http://hamcrest.org/
# https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all/1.3

prebuilt_jar(
    name = 'hamcrest',
    binary_jar = 'hamcrest-all-1.3.jar',
    visibility = [
        '//engine/common/test:engine-common-test'
    ]
)
