# https://github.com/ktorio/ktor
# https://ktor.io
# https://bintray.com/kotlin/ktor/ktor/1.3.1#files/io%2Fktor%2Fktor-server-core%2F1.3.1

prebuilt_jar(
    name = 'ktor-server-core',
    binary_jar = 'ktor-server-core-1.3.0.jar',
    visibility = [
      '//bff/main:bff-lib'
    ]
)
