# https://github.com/qos-ch/slf4j
# http://www.slf4j.org/
# https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.30/

prebuilt_jar(
    name = 'slf4j-simple',
    binary_jar = 'slf4j-simple-1.7.30.jar',
    visibility = [
        '//bff/main:bff-app'
    ]
)
