# https://github.com/ktorio/ktor
# https://ktor.io
# https://bintray.com/kotlin/ktor/ktor#files/io%2Fktor%2Fktor-io-jvm%2F1.3.1

prebuilt_jar(
    name = 'ktor-io-jvm',
    binary_jar = 'ktor-io-jvm-1.3.1.jar',
    visibility = [
      '//bff/main:bff-app'
    ]
)
