# https://github.com/ktorio/ktor
# https://ktor.io
# https://bintray.com/kotlin/ktor/ktor/1.3.1#files/io%2Fktor%2Fktor-server-host-common%2F1.3.1

prebuilt_jar(
    name = 'ktor-server-host-common',
    binary_jar = 'ktor-server-host-common-1.3.1.jar',
    visibility = [
      '//bff/main:bff-lib'
    ]
)
