# https://github.com/jetbrains/kotlin
# https://kotlinlang.org/api/latest/kotlin.test/index.html
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test/1.3.61

prebuilt_jar(
    name = 'kotlin-test-jvm',
    binary_jar = 'kotlin-test-1.3.61.jar',
    visibility = [ 'PUBLIC' ]
)
