# https://github.com/ktorio/ktor
# https://ktor.io
# https://mvnrepository.com/artifact/io.ktor/ktor-server-netty/1.3.0

prebuilt_jar(
    name = 'ktor-server-netty',
    binary_jar = 'ktor-server-netty-1.3.0.jar',
    visibility = [ 'PUBLIC' ]
)
