# https://github.com/netty/netty
# https://netty.io/index.html
# https://dl.bintray.com/netty/downloads/netty-4.1.46.Final.tar.bz2

prebuilt_jar(
    name = 'netty-common',
    binary_jar = 'netty-common-4.1.46.Final.jar',
    visibility = [
        '//bff/main:bff-app'
    ]
)
