# https://github.com/Kotlin/kotlinx.coroutines
# https://kotlinlang.org/docs/reference/coroutines-overview.html
# https://bintray.com/kotlin/kotlinx/kotlinx.coroutines/1.3.3#files/org%2Fjetbrains%2Fkotlinx%2Fkotlinx-coroutines-core%2F1.3.3

prebuilt_jar(
    name = 'kotlinx-coroutines-core',
    binary_jar = 'kotlinx-coroutines-core-1.3.3.jar',
    visibility = [
        '//bff/main:bff-app'
    ]
)
